version: '3.8'

services:
  mongodb:
    image: mongo:latest # Specify version instead of latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lnr-network

volumes:
  mongo-data:
    driver: local

networks:
  lnr-network:
    external: true
